# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Docker image

on: push
#   release:
#     types: [published]

jobs:
  build-cointainer:
    name: Build Docker container image
    runs-on: ubuntu-latest
    steps: 
#      - name: checkout code
#        uses: action/checkout@v2
#      - name: Publish to GitHub Packages
#        uses: docker/build-push-action@v1
#        with:
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}
     - name: Push to DockerHub
       uses: docker/build-push-action@v1
       with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: latest, ${{ github.run_number }}

