# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Docker image

on: push
#   release:
#     types: [published]

jobs:
  build-cointainer:
    name: Build Docker container image
    runs-on: ubuntu-latest
    steps: 
#      - uses: actions/checkout@v2
     - name: checkout code
       uses: actions/checkout@v2
     - name: Publish to Docker Hub 
       uses: docker/build-push-action@v1
       with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile
#         repository: my/repository
        tags: latest, ${{ github.run_number }}
        

#      - name: Push to DockerHub
#        uses: docker/build-push-action@v1
#        with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}
#           tags: latest, ${{ github.run_number }}

